<aside>
    <ul class="main-list">
        <li class="list-item main-menu">
            <a href="#">
                <i class="fa fa-paper-plane-o"></i>
                <span class="item">Projetos</span>
                <i class="fa fa-plus go-right"></i>
            </a>
            <ul class="sub-list">
                <li class="list-item sub-menu">
                    <a href="management.php">
                        <i class="fa fa-keyboard-o"></i>
                        <span class="item">Gerenciamento</span>
                    </a>
                </li>
                <li class="list-item sub-menu">
                    <a href="teams.php">
                        <i class="fa fa-cubes"></i>
                        <span class="item">Equipes</span>
                    </a>
                </li>
                <li class="list-item sub-menu">
                    <a href="proposals.php">
                        <i class="fa fa-percent"></i>
                        <span class="item">Propostas</span>
                    </a>
                </li>
                <li class="list-item sub-menu">
                    <a href="services.php">
                        <i class="fa fa-wrench"></i>
                        <span class="item">Serviços</span>
                    </a>
                </li>
            </ul>
        </li>

        <li class="list-item main-menu">
            <a href="#">
                <i class="fa fa-comments-o"></i>
                <span class="item">Gestão de Pessoas</span>
                <i class="fa fa-plus go-right"></i>
            </a>
            <ul class="sub-list">
                <li class="list-item sub-menu">
                    <a href="hiring.php">
                        <i class="fa fa-binoculars"></i>
                        <span class="item">Processo Seletivo</span>
                    </a>
                </li>
                <li class="list-item sub-menu">
                    <a href="members.php">
                        <i class="fa fa-users"></i>
                        <span class="item">Membros</span>
                    </a>
                </li>
                <li class="list-item sub-menu">
                    <a href="training.php">
                        <i class="fa fa-sitemap"></i>
                        <span class="item">Capacitações</span>
                    </a>
                </li>
                <li class="list-item sub-menu">
                    <a href="performance.php">
                        <i class="fa fa-tachometer"></i>
                        <span class="item">Avaliação de Desempenho</span>
                    </a>
                </li>
                <li class="list-item sub-menu">
                    <a href="satisfação.php">
                        <i class="fa fa-tasks"></i>
                        <span class="item">Pesquisa de Clima</span>
                    </a>
                </li>
            </ul>
        </li>

        <li class="list-item main-menu">
            <a href="#">
                <i class="fa fa-paint-brush"></i>
                <span class="item">Marketing</span>
                <i class="fa fa-plus go-right"></i>
            </a>
            <ul class="sub-list">
                <li class="list-item sub-menu">
                    <a href="communication.php">
                        <i class="fa fa-camera-retro"></i>
                        <span class="item">Comunicação</span>
                    </a>
                </li>
                <li class="list-item sub-menu">
                    <a href="crm.php">
                        <i class="fa fa-coffee"></i>
                        <span class="item">CRM</span>
                    </a>
                </li>
                <li class="list-item sub-menu">
                    <a href="tasks.php">
                        <i class="fa fa-pie-chart"></i>
                        <span class="item">Pesquisas</span>
                    </a>
                </li>
                <li class="list-item sub-menu">
                    <a href="events.php">
                        <i class="fa fa-ticket"></i>
                        <span class="item">Eventos</span>
                    </a>
                </li>
            </ul>
        </li>

        <li class="list-item main-menu">
            <a href="#">
                <i class="fa fa-puzzle-piece"></i>
                <span class="item">Stakeholders</span>
                <i class="fa fa-plus go-right"></i>
            </a>
            <ul class="sub-list">
                <li class="list-item sub-menu">
                    <a href="clients.php">
                        <i class="fa fa-diamond"></i>
                        <span class="item">Clientes</span>
                    </a>
                </li>
                <li class="list-item sub-menu">
                    <a href="partners.php">
                        <i class="fa fa-gears"></i>
                        <span class="item">Parceiros</span>
                    </a>
                </li>
            </ul>
        </li>

        <li class="list-item main-menu">
            <a href="#">
                <i class="fa fa-book"></i>
                <span class="item">Administrativo</span>
                <i class="fa fa-plus go-right"></i>
            </a>
            <ul class="sub-list">
                <li class="list-item sub-menu">
                    <a href="contracts.php">
                        <i class="fa fa-edit"></i>
                        <span class="item">Contratos</span>
                    </a>
                </li>
                <li class="list-item sub-menu">
                    <a href="records.php">
                        <i class="fa fa-pencil"></i>
                        <span class="item">Atas</span>
                    </a>
                </li>
                <li class="list-item sub-menu">
                    <a href="audits.php">
                        <i class="fa fa-check"></i>
                        <span class="item">Auditorias</span>
                    </a>
                </li>
            </ul>
        </li>

        <li class="list-item main-menu">
            <a href="#">
                <i class="fa fa-bar-chart"></i>
                <span class="item">Financeiro</span>
                <i class="fa fa-plus go-right"></i>
            </a>
            <ul class="sub-list">
                <li class="list-item sub-menu">
                    <a href="intake.php">
                        <i class="fa fa-arrow-right"></i>
                        <span class="item">Receitas</span>
                    </a>
                </li>
                <li class="list-item sub-menu">
                    <a href="outlet.php">
                        <i class="fa fa-arrow-left"></i>
                        <span class="item">Despesas</span>
                    </a>
                </li>
                <li class="list-item sub-menu">
                    <a href="payable.php">
                        <i class="fa fa-money"></i>
                        <span class="item">Contas a Receber</span>
                    </a>
                </li>
                <li class="list-item sub-menu">
                    <a href="receivable.php">
                        <i class="fa fa-credit-card"></i>
                        <span class="item">Contas a pagar</span>
                    </a>
                </li>
                <li class="list-item sub-menu">
                    <a href="flow.php">
                        <i class="fa fa-line-chart"></i>
                        <span class="item">Fluxo de Caixa</span>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</aside>